language: php
php:
  - 5.3
  - 5.5
  - 5.4
script: 
  - sh -c "./lib/Cake/Console/cake test app Controller/UsersController"
  - sh -c "./lib/Cake/Console/cake test app Controller/MessagesController"
notifications:
  email: false