language: php
php:
  - 5.5
  - 5.4
  - hhvm
script: 
  - sudo lib/Cake/Console/cake test app Controller/UsersController
  - sudo lib/Cake/Console/cake test app Controller/MessagesController

notifications:
  email: false